### ISSUE TITLE
Having ErrorException in EncryptionServiceProvider.php line 25:

### ISSUE THREAD

**Issue by Ahnaf** [SlovakNationalGallery/webumenia.sk#232]
I am trying to install this project to Homestead on windows 10 machine.  
After installation I am having following error in all version of php 7.0, 7.1, 7.2
ErrorException in EncryptionServiceProvider.php line 25: 

Even I have installed mcrypt and so on. 
Please help.

**Comment by eronisko** [comment]
FWIW, [Dockerfile](https://github.com/SlovakNationalGallery/webumenia.sk/blob/3bcb3b5b98961d1c671f8514703a604447f2524c/Dockerfile) on develop branch lists required system dependencies.

**Comment by Ahnaf** [comment]
Thanks a lot. Is there any guide to host this code in single machine without docker?

**Comment by igor-kamil** [comment]
try to use PHP5.6 and follow instructions: https://github.com/SlovakNationalGallery/webumenia.sk#local-installation 
it's laravel based app. so for more info, check https://laravel.com/docs/5.2/installation
regarding your exception - it seems like you are missing "mcrypt" extension. try to install it. 
good luck. in case of troubles let us know.

**Comment by eronisko** [comment]
@Ahnaf have you been able to get this up and running?

**Comment by eronisko** [comment]
Closing this due to no response. Please feel free to re-open if you're still having issues.
