### ISSUE TITLE
English (hungarian, chinese...) language versions?

### ISSUE THREAD

**Issue by andrejm** [SlovakNationalGallery/webumenia.sk#3]
As I wanted to tweet about web umenia, I realized the search functionality would have little value for non-Slovaks. Any plans for translations of web umenia user interface? Would make sense in case of Slovak art showcase I guess...?

(this is more of a question/suggestion than bug report ;)

**Comment by igor-kamil** [comment]
it's definitely in our plans. we just didn't started yet. (but soon we will)
would you like to contribute?

**Comment by andrejm** [comment]
Sure, I can cover English & probably Czech versions :) Might even get someone for German language, but not sure.

**Comment by phivk** [comment]
hi @andrejm ! I have been working on i18n the past few months. For now it has resulted in English version of the full interface: https://www.webumenia.sk/en

All static texts are translated via language files:
https://github.com/SlovakNationalGallery/web-umenia-2/tree/master/resources/lang/en

In the near future we expect to work on translating the [Czech language strings](https://github.com/SlovakNationalGallery/web-umenia-2/tree/master/resources/lang/cs),
 which are already set up.

Next to that we are currently making it possible for the database to contain translation values for relevant fields. This involves adding new db tables via migrations, updating the admin interface, and creating 2 separate Elasticsearch indices for SK and EN.

Is there anything among this you might like to contribute to? For example the Czech translations?
Let me know and Ill happily walk your through more details!

**Comment by andrejm** [comment]
Hi @phivk thumbs up & sorry for late reply! Sure, I'll be able to help with Czech translation – I suppose pull requests are OK with you? Any special instructions?

**Comment by phivk** [comment]
@andrejm yes, creating Pull Requests is the way to go 👍 
Please submit a PR to the `feature/i18n-translation` as base branch.

For Czech translations, please check out the 'cs' language files directory:
https://github.com/SlovakNationalGallery/web-umenia-2/tree/master/resources/lang/cs
It contains a separate language file for each front end template + one for general terms. Some of the values in these files are already translated into Czech, but most of them are still in Slovak. This is the best place to start I think...

One thing to note is that @igor-kamil has some some Czech translations still on another branch. 
@igor-kamil could you please merge those changes into `feature/i18n-translation`, to preven @andrejm doing double work?

**Comment by igor-kamil** [comment]
Hi @andrejm ! Thank you for your initiative!
But @phivk is right. Within the following days I will merge existing cezch translation files from other branch back to develop - what will be better point to start from.
 We will let you know soon!

**Comment by andrejm** [comment]
OK, ping this thread then pls.

**Comment by eronisko** [comment]
I think this issue is now fulfilled. Let us know if you think it should be re-opened.
