### ISSUE TITLE
A few UX / accessibility suggestions

### ISSUE THREAD

**Issue by ajobi** [SlovakNationalGallery/webumenia.sk#456]
### 1. Inaccessible tap targets
Some of the interactive elements of the website are seemingly not built with touch in mind (e.g. too small for users to be able to confidently tap them). Examples can to be found in the main navigation elements of the site f.e.:
<img width="109" alt="Screenshot 2021-02-26 at 18 47 27" src="https://user-images.githubusercontent.com/22252756/109336190-577f7b80-7863-11eb-9fd9-a4bf1a6eaefd.png">
<img width="369" alt="Screenshot 2021-02-26 at 18 39 41" src="https://user-images.githubusercontent.com/22252756/109336195-59493f00-7863-11eb-8808-546930fa6869.png">

It is recommended to make the interactive elements at least ~46x46px big and ideally keep some space between them for comfortable mobile experience. 
https://web.dev/accessible-tap-targets/

### 2. Bad contrast

The color of the search placeholder has too little contrast with the background. It adds unnecessary strain on the eye and can be difficult to read especially for older visitors:
<img width="298" alt="Screenshot 2021-02-26 at 18 40 34" src="https://user-images.githubusercontent.com/22252756/109337007-76cad880-7864-11eb-9695-ef10a5ddcf9e.png">
<img width="742" alt="Screenshot 2021-02-26 at 18 57 40" src="https://user-images.githubusercontent.com/22252756/109337044-834f3100-7864-11eb-83df-a475fcb499c2.png">

The placeholder should ideally have a contrast ratio of at least 3:1, [maybe more](https://accessibleweb.com/question-answer/does-placeholder-text-need-to-meet-color-contrast-requirements/#:~:text=Placeholder%20text%20must%20meet%20a,satisfy%20WCAG%202.0%20AA%20requirements.&text=3)

Another instance of bad contrast can be found in slider. The text is very difficult to read with lighter images:
<img width="799" alt="Screenshot 2021-02-26 at 19 03 18" src="https://user-images.githubusercontent.com/22252756/109338229-42f0b280-7866-11eb-98b7-b0afa3ebe28d.png">

Here are some of the standard solutions you could use to solve this common problem:
https://blog.iamsuleiman.com/techniques-to-display-text-overlay-background-images/

**Comment by eronisko** [comment]
Thank you for the feedback 👍 We'll keep this in mind for the upcoming design updates.
