### ISSUE TITLE
provide captions for images in slider

### ISSUE THREAD

**Issue by monolithpl** [SlovakNationalGallery/webumenia.sk#46]
a great project and fantastic window on slovak art, but having picked lovely images for the sliders, add captions to them - this defeats the whole purpose of showcasing art! you have a fantastic woodcut by edita ambrušová in your winter gallery - i had to open developer tools, check out the url behind slider div, paste that into google images just to find out who the artist was. surely a major flaw in a site designed to promote the artists

**Comment by monolithpl** [comment]
or - also logically - make sure one of the first results of the search page you redirect to (in this case, winter+cold+slow https://www.webumenia.sk/katalog?search="zima"+"zimna"+"zimny"+"sneh"&has_image=1&sort_by=view_count) is the picture people originally clicked from the slider

**Comment by phivk** [comment]
Hi @monolithpl thanks a lot for reporting!
I understand it must be frustrating seeing an image you like in the carousel on the home page:
![screen shot 2018-01-03 at 12 46 36](https://user-images.githubusercontent.com/902958/34519425-2d17a364-f084-11e7-94cb-20600f7f1b16.png)
and being unable (not counting your awesome devtools + gImages trick) to the artwork's 'source page':
https://www.webumenia.sk/dielo/SVK:OGD.G_239

I'd like to discuss solutions to this issue with our designer and editors. So far I see the following potential solutions:

1. provide captions underneath carousel
2. provide `title` attributes that are visible on hover (insufficient on mobile)
3. make sure one of the first results of the search page you redirect to is the picture people originally clicked from the slider/carousel on the homepage

... or a combination of the above. 
Are there other options I have missed?

@ustengrav what do you think?

**Comment by monolithpl** [comment]
i think any of the three would be a help, but the least intrusive - in terms of design and functionality - would be option 3, just a line or two added to the code to check if an image is in the carousel and if it is and matches the search terms, then bring it to the top

**Comment by phivk** [comment]
thanks @monolithpl , my thoughts:

**option 1**: not sure about adding an extra captions element, which could make the design of the home page look cluttered.

**option 2**: quite nonintrusive, but now that I think about it, providing info about the source artwork as `title` on hover might not make sense considering clicking a carousel image will lead you to a something different than that artwork, i.e. search results / article / collection / external website. 

Thinking about it like this, it would make sense to expect the source artwork that is previewed in the carousel to be findable in the target page that the carousel links to (whether that is a search result / article / collection / external website). If we agree on this, the challenge is to ensure the source artwork is (prominently) featured in the target page: in this case on the search result page.

which brings us to **option 3**: I like the idea of leveraging existing UI patterns, thereby alleviating the need to add captions underneath the home page carousel. It also fits with what users might expect from clicking the preview image in the carousel as I explained above.

Not sure how easily this is implemented as search results are fetched and sorted by ElasticSearch, which would need to know whether artworks are used in the carousel. Another potential way to implement this would be to encode the id of the carousel artwork as a url parameter...

I wonder what @igor-kamil has to say about implementation?

**Comment by martin-havala** [comment]
just a check: 
for collections artworks are ordered in a way author has selected them (so first one could be selected as a carousel pic also), but if there is also an article, this may be not that straightforward, 
e.g. sometimes the carousel pic is not included in collection (like on https://www.webumenia.sk/en/kolekcia/178)

maybe small icon like 🖼 in the carousel corner could help? But for now carousel images are stored separately, so for now there is no direct link between image and artwork description, even if it's using some artwork from database ¯\_(ツ)_/¯

**Comment by ustengrav** [comment]
yes, artworks in a collection can be ordered by the author, but it does not always make sense for the cover artwork to be the first in the list

often there is a link in the carousel to the custom (filtered) search of the artworks and then there is no reliable way right now to make the carousel artwork be on the top

currently, the carousel options are: title, description, image, url and published/unpublished checkbox

maybe another field can be added either with a description or a secondary link (both are imperfect solutions as mentioned above)... I don't think the carousel item should lead to 2 different places. 

having the carousel artwork as a first one in the collection might be the best compromise (since if it's an article, the artwork is definitely there and findable), but we would have to solve the custom search usecase (that's even the one monolithpl was refering to originally)...

We can discuss the options further sometimes.

**Comment by eronisko** [comment]
Thank you for reporting this. Since we've moved away from the 'Slides' design on the front page, I believe this issue can be closed. Feel free to re-open.
